---
apiVersion: v1
kind: Service
metadata:
  name: reids-app-service
  labels:
    author: intelliqit
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
   name: redis-app
...
